### ISSUE TITLE
Unclear function name

### ISSUE THREAD

**Issue by andrei-kubarkov** [nikita-kubarkov/MyGame#7]
Move it closer to "setupGame" and give it a proper name. 
Most functions DO something with someTHING. So naming most often is "verbNoun". e.g. "startNewGame" or "restartGame", sometimes maybe just "restart" or "reload", but that it is less recommended.
In your case "newGame" - does not tell what do you DO with a new name.

https://github.com/nikita-kubarkov/MyGame/blob/79047824a642df1fd0cfc2668201563ce7bf82a8/JS/index.js#L23

**Comment by nikita-kubarkov** [comment]
всё
